spring:
  cloud:
    config:
      label: master
      profile: prod
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-service/discovery-server/eureka/
  instance:
    instance-id: gateway-service
    prefer-ip-address: true
