eureka:
  instance:
    instance-id: demo-gateway-service
    prefer-ip-address: true
    ip-address: 120.77.58.15
  client: #服务提供者provider注册进eureka服务列表内
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://120.77.58.15:8090/eureka/