eureka:
  client:
    register-with-eureka: true  # Register the service with Eureka
    fetchRegistry: true         # Fetch the registry from Eureka
    service-url:
      defaultZone: http://eureka-service:32011/eureka  # Point to the Eureka service within Kubernetes

  instance:
    instance-id: example-service
    prefer-ip-address: true  # Use the IP address for accessing the service

spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/demo  # PostgreSQL connection URL (change if necessary)
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
    type: com.zaxxer.hikari.HikariDataSource
    initialization-mode: always
    continue-on-error: true
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: SpringBootDemoHikariCP
      max-lifetime: 60000
      connection-timeout: 30000