apiVersion: v1
kind: Service
metadata:
  name: config
spec:
  selector:
    app: config
  ports:
    - protocol: TCP
      port: 32014
      targetPort: 32014
      nodePort: 32014
  type: NodePort  # Change to NodePort if needed

