apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  selector:
    app: eureka
  ports:
    - protocol: TCP
      port: 32011
      targetPort: 32011
      nodePort: 32011
  type: NodePort  # Change to NodePort if needed

