apiVersion: v1
kind: Service
metadata:
  name: example
spec:
  selector:
    app: example
  ports:
    - protocol: TCP
      port: 32013
      targetPort: 32013
      nodePort: 32013
  type: NodePort  # Change to NodePort if needed

