apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-nginx
  name: my-nginx
  namespace: default
spec:
  clusterIP: 10.106.39.10
  clusterIPs:
  - 10.106.39.10
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - nodePort: 32010
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: my-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
