server:
  port: 8093
eureka:
  client:
    register-with-eureka: true  # Register the service with Eureka
    fetchRegistry: true         # Fetch the registry from Eureka
    service-url:
      defaultZone: http://localhost:8090/discovery-server/eureka/  # Point to the Eureka service within Kubernetes

  instance:
    instance-id: config-server
    prefer-ip-address: true  # Use the IP address for accessing the service